-- Update SQL to set cover image paths
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/1_Moby-Dick.jpg' WHERE "Id" = 1;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/2_The Odyssey.jpg' WHERE "Id" = 2;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/3_War and Peace.jpg' WHERE "Id" = 3;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/4_Crime and Punishment.jpg' WHERE "Id" = 4;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/5_Jane Eyre.jpg' WHERE "Id" = 5;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/6_Wuthering Heights.jpg' WHERE "Id" = 6;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/7_Great Expectations.jpg' WHERE "Id" = 7;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/8_The Brothers Karamazov.jpg' WHERE "Id" = 8;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/9_Animal Farm.jpg' WHERE "Id" = 9;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/10_The Grapes of Wrath.jpg' WHERE "Id" = 10;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/11_Little Women.jpg' WHERE "Id" = 11;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/12_Catch-22.jpg' WHERE "Id" = 12;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/13_The Alchemist.jpg' WHERE "Id" = 13;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/14_Don Quixote.jpg' WHERE "Id" = 14;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/15_Fahrenheit 451.jpg' WHERE "Id" = 15;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/16_Slaughterhouse-Five.jpg' WHERE "Id" = 16;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/17_Dracula.jpg' WHERE "Id" = 17;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/18_Frankenstein.jpg' WHERE "Id" = 18;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/19_Les Misérables.jpg' WHERE "Id" = 19;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/20_The Picture of Dorian Gray.jpg' WHERE "Id" = 20;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/21_A Tale of Two Cities.jpg' WHERE "Id" = 21;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/22_The Scarlet Letter.jpg' WHERE "Id" = 22;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/23_The Adventures of Huckleberry Finn.jpg' WHERE "Id" = 23;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/24_The Old Man and the Sea.jpg' WHERE "Id" = 24;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/25_One Hundred Years of Solitude.jpg' WHERE "Id" = 25;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/26_The Chronicles of Narnia.jpg' WHERE "Id" = 26;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/27_Dune.jpg' WHERE "Id" = 27;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/28_The Shining.jpg' WHERE "Id" = 28;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/29_The Sun Also Rises.jpg' WHERE "Id" = 29;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/30_Rebecca.jpg' WHERE "Id" = 30;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/31_A Passage to India.jpg' WHERE "Id" = 31;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/32_The Kite Runner.jpg' WHERE "Id" = 32;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/33_The Girl with the Dragon Tattoo.jpg' WHERE "Id" = 33;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/34_Memoirs of a Geisha.jpg' WHERE "Id" = 34;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/35_The Handmaid's Tale.jpg' WHERE "Id" = 35;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/36_Gone with the Wind.jpg' WHERE "Id" = 36;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/37_Life of Pi.jpg' WHERE "Id" = 37;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/38_The Hunger Games.jpg' WHERE "Id" = 38;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/39_Ender's Game.jpg' WHERE "Id" = 39;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/40_The Road.jpg' WHERE "Id" = 40;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/41_The Fault in Our Stars.jpg' WHERE "Id" = 41;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/42_Beloved.jpg' WHERE "Id" = 42;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/43_The Book Thief.jpg' WHERE "Id" = 43;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/44_The Secret Garden.jpg' WHERE "Id" = 44;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/45_A Clockwork Orange.jpg' WHERE "Id" = 45;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/46_Lolita.jpg' WHERE "Id" = 46;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/47_Persuasion.jpg' WHERE "Id" = 47;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/48_Murder on the Orient Express.jpg' WHERE "Id" = 48;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/49_The Count of Monte Cristo.jpg' WHERE "Id" = 49;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/50_Treasure Island.jpg' WHERE "Id" = 50;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/51_The Hitchhiker's Guide to the Galaxy.jpg' WHERE "Id" = 51;
UPDATE "Books" SET "CoverImagePath" = '/uploads/covers/52_Charlotte's Web.jpg' WHERE "Id" = 52;
